* umlauts layer
Make better use of umlauts when using a German keyboard layout.

The German keyboard layout is inconvenient for programming and navigation in
Spacemacs because the =[]{}\= keys are at located inconveniently. At the
location of these keys in the (much more suitable) American layout, the German
keyboard layout has the umlauts =öäÖÄü=. Fortunately, these umlauts are
relatively rare in German words, they are useless when working in a
different language, and they are not bound by Spacemacs.

The layer provides functionality to remap =öäÖÄü= to =[]{}\=.

1. When =umlauts-remap-when-not-mapped= is set, =öäÖÄ= are mapped to =[]{}=
   whenever the former are unbound (e.g., in Evil's normal mode). This
   functionality is enabled by default.
2. This layer provides a minor mode called =global-umlaut-minor-mode=, which
   globally remaps =öäÖÄü= to =[]{}\=. When the mode is active, umlauts can
   still be typed by also pressing the control key (e.g., =C-ö= produces
   character =ö=). The =global-umlauts-minor-mode= is disabled by default and
   can be toggled via =SPC tÄ= or =SPC t}=.

Layer configuration variables:
| =umlauts-remap-when-not-mapped= | Remap =öäÖÄ= to =[]{}= whereever they are unbound (default: =t=)                             |
| =umlauts-remap-initally=        | Globally enable the umlauts minor mode to remap =öäÖÄü= to =[]{}\= everywhere (default: =nil=) |
